CREATE TABLE [dbo].[CUSTOMERS] (
    [CUSTOMERID] NVARCHAR (10) NOT NULL,
    [FIRSTNAME]  NVARCHAR (50) NULL,
    [LASTNAME]   NVARCHAR (50) NULL,
    [EMAIL]      NVARCHAR (50) NULL,
    [HOUSENO]    NVARCHAR (50) NULL,
    [STREET]     NVARCHAR (50) NULL,
    [TOWN]       NVARCHAR (50) NULL,
    [POSTCODE]   NVARCHAR (10) NULL,
    CONSTRAINT [PK__CUSTOMER__61DBD78869B0F9E7] PRIMARY KEY CLUSTERED ([CUSTOMERID] ASC)
);

