CREATE TABLE [dbo].[ORDERITEMS] (
    [ORDERITEMID] INT            IDENTITY (1, 1) NOT NULL,
    [ORDERID]     INT            NULL,
    [PRODUCTID]   INT            NULL,
    [QUANTITY]    INT            NULL,
    [PRICE]       DECIMAL (9, 2) NULL,
    PRIMARY KEY CLUSTERED ([ORDERITEMID] ASC),
    FOREIGN KEY ([ORDERID]) REFERENCES [dbo].[ORDERS] ([ORDERID]),
    FOREIGN KEY ([PRODUCTID]) REFERENCES [dbo].[PRODUCTS] ([PRODUCTID])
);

