CREATE TABLE [dbo].[PRODUCTS] (
    [PRODUCTID]   INT           IDENTITY (1, 1) NOT NULL,
    [PRODUCTNAME] NVARCHAR (50) NULL,
    [COLOUR]      NVARCHAR (20) NULL,
    [SIZE]        NVARCHAR (20) NULL,
    PRIMARY KEY CLUSTERED ([PRODUCTID] ASC)
);

